### 异常

#### 概述：

> 异常：就是程序出现了不正常的情况

#### 体系：

- Throwable
  - Error	严重问题，不需要处理
    - Exception	称为异常类，他表示程序本身可以处理的问题
      - RuntimeException	  在编译期是不检查的，出现问题后，需要我们回来修改代码
      - 非RuntimeException  编译器就必须处理的，否则程序不能通过编译，就更不能正常运行了

#### JVM的默认处理方案：

> 如果程序出现了问体，我们没有做任何处理，最终JVM会做默认的处理

- 把异常的名称，异常原因及异常出现的位置等信息输出在了控制台
- 程序停止执行



#### 异常处理：

两种方法：

- try...catch...

  ```java
  try{
      可能出现异常的代码;
  }catch（异常类名 变量名）{
      异常的处理代码;
  }
  ```

  执行流程：

  程序从try里面的代码开始执行

  出现异常，会自动生成一个异常类对象，该异常对象将被提交给Java运行时系统

  当Java运行时系统接受到异常对象时，会到catch中去找匹配的异常类，找到后进行异常的处理

  执行完毕后，程序还可以继续往下执行

  [TryDemo.java](/./code/TryCatch/tryDemo.java)

  

- Throwable

| 方法名            | 说明                            |
| ----------------- | ------------------------------- |
| getMessage()      | 返回此throwable的详细消息字符串 |
| toString()        | 返回此可抛出的简短描述          |
| printStackTrace() | 把异常的错误信息输出在控制台    |

[tryDemo01.java](/./code/TryCatch/tryDemo01.java)

```java
System.out.println(e.getMessage()); //  Index 3 out of bounds for length 3
System.out.println(e.toString());   //  java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
e.printStackTrace();
//java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
//	at TryCatch.tryDemo01.method(tryDemo01.java:13)
//	at TryCatch.tryDemo01.main(tryDemo01.java:6)
```

- throws

虽然我们通过try...catch...可以对异常进行处理，但是并不是所有情况我们都有权限进行异常的处理，也就是说，有些时候可能出现的异常时我们处理不了的，针对这种情况，Java提供了throws的处理方案

格式：

> throws 异常类名;

注意：这个格式跟在方法的括号后面

- 编译时异常必须进行处理

  两种处理方案：try...catch...或者throws，如果采用throws这中方案，将来谁调用谁处理

- 运行异常可以不处理

  出现问题后，需要修改代码



#### throws 和 throw的区别

throws

- 用在方法声明后面，跟的是异常类名
- 表示抛出异常，由该方法的调用者来处理
- 表示出现异常的一种可能性，并不一定会发生这些异常

throw

- 用在方法体内，跟的是异常的对象名
- 表示抛出异常，由方法体内的一句处理
- 执行throw一定抛出了某种异常

[Demo.java](/./code/DIYexception/teacherDemo.java)